.\" Call make README after modifying this file.
.TH FDUP 1 "August 2013" "Robert Clausecker" "User Commands"

.SH NAME
fdup \- find duplicates

.SH SYNOPSIS
.B fdup
.RI [ MODE ]
.RI [ OPTION "...]"
.IR directory ...

.SH DESCRIPTION
.B fdup
traverses the supplied directories and finds file with equal contents.
.B fdup
outputs statistics to
.BR stderr (3)
while processing files.
.B fdup
will not follow symbolic links it encounters.

.SH OPTIONS

This utility has three modes of operation. These are selected with the options
.BR \-H ,
.B \-L
and
.BR \-S .
If none of these options is given,
.B fdup
behaves as if
.B \-S
was selected. If more than one mode of operation is given, only the last mode
that was passed counts.

.TP
\.B -H
Turn each group of files with equal contents into hardlinks to one file. This
currently implies
.BR \-x .
.TP
.B \-L
List groups of files with equal contents, separated by blank files.
.TP
.B \-S
Similar to
.BR \-H ,
Turn each group of files with equal contents into symbolic links to one file.
The file that is not turned into a symbolic link is arbitrarily chosen.
.TP
.B \-h
Print a brief help.
.TP
.B \-x
Stay on one file system. Supplying multiple directories on different file
systems with this option causes an error.

.SH BUGS
The program is quite slow as it needs to read every file it encounters. Future
versions of this program will employ smartes techniques to compare files. fdup
lacks configurability and options.

Please file bugs at <https://github.com/fuzxxl/fdup/issues>.

.SH COPYRIGHT
This program, its source code and this manpage is licensed under a 2-clause BSD
license. See file
.I COPYING
for details. 

.SH AUTHOR
Written by Robert Clausecker <fuzxxl@gmail.com>.
