.\" Call make README after modifying this file.
.TH FDUP 1 "August 2013" "Robert Clausecker" "User Commands"

.SH NAME
fdup \- find duplicates

.SH SYNOPSIS
.B fdup
.RI [ mode ]
.RI [ option "...]"
.IR directory ...

.SH DESCRIPTION
\fBfdup\fR traverses the supplied directories and finds file with equal
contents. \fBfdup\fR outputs statistics to \fBstderr\fR(3) while processing
files. \fBfdup\fR will not follow symbolic links it encounters.

.SH OPTIONS

This utility has four modes of operation. These are selected with the options
\fB-B\fR, \fB\-H\fR, \fB\-L\fR and \fB\-S\fR. If none of these options is
given, \fBfdup\fR behaves as if \fB\-S\fR was selected. If more than one mode
of operation is given, only the last mode that was passed counts.

.TP
.B \-B
Turn files with equal contents into \fBbtrfs\fR(8) lightweight copies of each
other. A lightweight or COW copy shares the underlying disk space with the
original file until you change it, but has no other connections to the original
file. This mode is preferable where applicable. This option only works on Linux
with files on \fBbtrfs\fR file systems and implies \fB-b \fId\fR.

.TP
.B \-H
Turn each group of files with equal contents into hardlinks to one file. This
implies \fB-b \fIdl\fR.

.TP
.B \-L
List groups of files with equal contents, separated by blank files.

.TP
.B \-S
Similar to \fB\-H\fR, turn each group of files with equal contents into
symbolic links to one file. The file that is not turned into a symbolic link is
arbitrarily chosen.

.TP
\fB\-b \fIspecifier\fR...
Control file matching behavior. \fIspecifier\fR is one or more of the following
specifiers. By default, \fBfdup\fR considers all cases as duplicate that can be
detected as distinct files with the specifiers below.

.RS
.TP
.B c
Files with different creation times are considered distinct
.TP
.B d
Files on different devices are considered distinct
.TP
.B g
Files owned by different groups are considered distinct
.TP
.B l
Hardlinks to the same file are considered distinct
.TP
.B m
Files with different modification times are considered distinct
.TP
.B p
Files with different permissions are considered distinct
.TP
.B u
Files owned by different users are considered distinct
.RE

.TP
.B \-h
Print a brief help.

.TP
.B \-p
Preserve permissions, ownership, modification and access times. If \fB\-p\fR is
provided and \fBfdup\fR fails to correctly assign one of these attributes, no
files are changed and \fBfdup\fR aborts. This differs from the behavior without
\fB\-p\fR, in that otherwise only a warning is printed and \fBfdup\fR keeps
going, possibly clobbering attributes of the file. \fBfdup\fR attempts to
preserve attributes regardless of \fB\-p\fR. Please notice that \fB\-p\fR has
no effect when used with \fB\-L\fR for obvious reasons. Only access and
modification times are preserved when used with \fB\-S\fR.

.TP
\fB\-s \fIn\fR[,\fIm\fR]
Restrict file size when looking for duplicates. If used in the form \fB\-s
\fIn\fR, \fBfdup\fR ignores all files that are less than \fIn\fR bytes in size.
If used in the form \fB\-s \fIn\fR,\fIm\fR, \fBfdup\fR ignores all files that
are less than \fIn\fR or more than \fIm\fR bytes in size. If you don't want to
specify a lower boundary, use \fB\-s \fI0\fR,\fIm\fR. By default, \fBfdup\fR
behaves as if \fB\-s \fI0\fR has been given.

Suffixes \fIK\fR, \fIM\fR, \fIG\fR, \fIT\fR, \fIP\fR and \fIE\fR can be used
to specify 1024, 1024*1024, 1024*1024*1024 etc. bytes.

This option can speed up operation if you are scanning a large amount of small
files but don't care about duplicates in them, or if you don't want \fBfdup\fR
to scan through very large files that are known not to be duplicates.

.TP
.B \-x
Stay on one file system. This applies to each supplied directory individually.

.SH EXIT STATUS
\fBfdup\fR terminates with an exit status of 0 on success. If one of the
operations \fBfdup\fR performs fails, its exit status is 1. If \fBfdup\fR does
not recognize one of the command line options it was called with, it terminates
with an exit status of 2.

.SH BUGS
When using the option \fB\-H\fR, \fBfdup\fR is known to have problems when too
many files are considered equal.

Please file bugs at <https://github.com/fuzxxl/fdup/issues>.

.SH COPYRIGHT
This program, its source code and this manpage is licensed under a 2-clause BSD
license. See file
.I COPYING
for details. 

.SH AUTHOR
Written by Robert Clausecker <fuzxxl@gmail.com>.
